import React from 'react';
import { motion } from 'framer-motion';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const CookiePolicyPage = () => {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.2,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { type: 'spring', stiffness: 100, damping: 15 }
    }
  };

  const sections = [
    {
      title: '1. What Are Cookies?',
      content: 'Cookies are small text files that are placed on your device (computer, tablet, mobile phone) when you visit our website. They contain information about your browsing activity and preferences. Cookies allow websites to remember information about your visit, which can make your next visit easier and the website more useful to you.'
    },
    {
      title: '2. How We Use Cookies',
      content: 'UNAVO uses cookies to enhance your user experience, improve our website functionality, and analyze how our website is being used. Cookies help us to remember your preferences, understand how you interact with our site, and provide you with personalized content and advertisements.'
    },
    {
      title: '3. Types of Cookies We Use',
      content: 'Necessary Cookies: These cookies are essential for the website to function properly. They enable basic functions like page navigation and access to secure areas. Session Cookies: These cookies exist only during your browsing session and are deleted when you close your browser. Persistent Cookies: These cookies remain on your device for a specified period or until you manually delete them. Analytics Cookies: These cookies help us understand how visitors interact with our website by collecting and reporting information. Marketing Cookies: These cookies are used to deliver personalized advertisements and marketing messages based on your interests and browsing behavior.'
    },
    {
      title: '4. Third-Party Cookies',
      content: 'We may also allow third-party service providers (such as analytics companies, advertising partners, and social media platforms) to place cookies on your device. These third-party cookies are used to provide services such as website analytics, customer relationship management, and targeted advertising. These third parties have their own privacy policies and cookie policies.'
    },
    {
      title: '5. Your Consent',
      content: 'By continuing to use our website, you consent to our use of cookies as described in this Cookie Policy. If you do not agree with our use of cookies, you may disable cookies through your browser settings. However, please note that disabling cookies may affect your ability to access certain features of our website.'
    },
    {
      title: '6. Cookie Duration',
      content: 'Cookies have different lifespans depending on their type. Session cookies are automatically deleted when you close your browser. Persistent cookies remain on your device for the duration specified in their settings, which can range from days to years. You can check the specific lifespan of cookies in your browser settings.'
    },
    {
      title: '7. How to Control Cookies',
      content: 'Most web browsers allow you to control cookies through their settings. You can typically: Accept all cookies; Block certain types of cookies; Delete cookies already stored on your device; Receive a notification when a cookie is being set. Please note that the steps to manage cookies vary depending on your browser. Consult your browser\'s help menu or visit www.allaboutcookies.org for more information.'
    },
    {
      title: '8. Disabling Cookies',
      content: 'If you choose to disable cookies, some features of our website may not function properly. This could include features such as remembering your login information, maintaining your shopping cart, and receiving personalized recommendations. We recommend keeping cookies enabled for the best user experience.'
    },
    {
      title: '9. Google Analytics',
      content: 'Our website uses Google Analytics, a web analytics service provided by Google, Inc. Google Analytics uses cookies to help us analyze how users use our site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google\'s behalf.'
    },
    {
      title: '10. Advertising Cookies',
      content: 'UNAVO may use cookies for targeted advertising purposes. These cookies may track your browsing activity across different websites to deliver personalized advertisements. You can opt out of personalized advertising by adjusting your privacy settings in your browser or by visiting industry opt-out platforms.'
    },
    {
      title: '11. Security of Cookies',
      content: 'While cookies are text files and cannot execute code or transmit viruses, they may contain personally identifiable information. We use appropriate security measures to protect cookie data and prevent unauthorized access. Always ensure that your device has updated security software.'
    },
    {
      title: '12. Updates to This Cookie Policy',
      content: 'UNAVO reserves the right to update this Cookie Policy from time to time to reflect changes in our cookie practices, technology, legal requirements, or other factors. Any changes to this Cookie Policy will be posted on this page with an updated "Last Updated" date. Your continued use of our website following the posting of revisions means that you accept and agree to the changes.'
    },
    {
      title: '13. Contact Us',
      content: 'If you have any questions or concerns about our Cookie Policy or our use of cookies, please contact us at kumarankarthikeyan14@gmail.com or call us at +91 8248701817. We are happy to address your concerns and provide clarification regarding our cookie practices.'
    },
    {
      title: '14. Do Not Track Signals',
      content: 'Some browsers include a "Do Not Track" feature. Our website does not currently respond to Do Not Track signals due to the lack of an industry-wide standard. However, you can disable cookies and use other tracking prevention tools available in your browser.'
    },
    {
      title: '15. Cookie Consent Banner',
      content: 'When you first visit our website, you may see a cookie consent banner. This banner informs you about our use of cookies and allows you to accept or reject non-essential cookies. You can change your cookie preferences at any time by clicking on the cookie settings link in the footer of our website.'
    }
  ];

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* Navbar */}
      <Navbar showBackButton={true} />

      {/* Hero Section */}
      <section className="relative w-full py-20 bg-gradient-to-r from-green-500 via-emerald-500 to-green-600 text-white overflow-hidden">
        {/* Animated background circles */}
        <motion.div
          className="absolute top-10 left-10 w-40 h-40 bg-white opacity-10 rounded-full"
          animate={{ y: [0, 20, 0] }}
          transition={{ duration: 4, repeat: Infinity }}
        />
        <motion.div
          className="absolute bottom-10 right-10 w-32 h-32 bg-white opacity-10 rounded-full"
          animate={{ y: [0, -20, 0] }}
          transition={{ duration: 4, repeat: Infinity }}
        />

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center"
          >
            <h1 className="text-4xl md:text-5xl font-black mb-4 drop-shadow-lg">Cookie Policy</h1>
            <p className="text-xl opacity-90 drop-shadow">
              Learn how UNAVO uses cookies to enhance your browsing experience.
            </p>
            <p className="text-sm opacity-80 mt-4">Last updated: December 2025</p>
          </motion.div>
        </div>

        {/* Wave divider */}
        <svg
          className="absolute bottom-0 left-0 w-full h-20"
          viewBox="0 0 1200 120"
          preserveAspectRatio="none"
        >
          <path
            d="M0,50 Q300,0 600,50 T1200,50 L1200,120 L0,120 Z"
            fill="white"
          />
        </svg>
      </section>

      {/* Content Section */}
      <section className="py-16 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="mb-12 p-6 bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-200 rounded-xl"
          >
            <h2 className="text-2xl font-bold text-gray-800 mb-3">🍪 Introduction</h2>
            <p className="text-gray-700">
              This Cookie Policy explains how UNAVO ("we," "us," "our," or "Company") uses cookies and similar tracking technologies on our website. We are committed to transparency in our data collection practices and want you to understand how we use cookies to improve your browsing experience.
            </p>
          </motion.div>

          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true }}
            className="space-y-8"
          >
            {sections.map((section, index) => (
              <motion.div
                key={index}
                variants={itemVariants}
                className="border-l-4 border-green-500 pl-6 py-4 hover:bg-green-50 transition rounded-r-lg pr-6"
              >
                <h2 className="text-2xl font-bold text-gray-800 mb-3">{section.title}</h2>
                <p className="text-gray-700 leading-relaxed">{section.content}</p>
              </motion.div>
            ))}
          </motion.div>

          {/* Additional Info */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="mt-12 p-6 bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-200 rounded-xl"
          >
            <h3 className="text-xl font-bold text-gray-800 mb-3">⚙️ Managing Your Preferences</h3>
            <p className="text-gray-700 mb-4">
              You have the right to manage your cookie preferences. Most browsers allow you to refuse cookies and alert you when a cookie is being sent. You can also delete cookies that have already been set. The methods for doing so vary from browser to browser, and from version to version.
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2">
              <li>Google Chrome: Settings → Privacy and Security → Cookies and other site data</li>
              <li>Firefox: Preferences → Privacy & Security → Cookies and Site Data</li>
              <li>Safari: Preferences → Privacy → Manage Website Data</li>
              <li>Microsoft Edge: Settings → Privacy, search, and services → Clear browsing data</li>
            </ul>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <Footer />
    </div>
  );
};

export default CookiePolicyPage;
